# These links will appear as a "Sponsor" button on your GitHub repository.
# Supported options: github, patreon, open_collective, ko_fi, tidelift, community_bridge,
#                    liberapay, issuehunt, otechie, lfx_crowdfunding, polar, buy_me_a_coffee, thanks_dev, custom

github: [Nikos-kts]
